// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlS-5rA9AXrgY0U2-Mh3M4jBPL1jE3daA',
    appId: '1:124179968487:web:c967af86ad05f27bef8d42',
    messagingSenderId: '124179968487',
    projectId: 'knowledgematch-3a567',
    authDomain: 'knowledgematch-3a567.firebaseapp.com',
    storageBucket: 'knowledgematch-3a567.appspot.com',
    measurementId: 'G-XHSS4JFX3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG1nq8eJvOsH0hDMMXesHPs70v6zEfyfw',
    appId: '1:124179968487:android:1aa51b8f5fe9cdadef8d42',
    messagingSenderId: '124179968487',
    projectId: 'knowledgematch-3a567',
    storageBucket: 'knowledgematch-3a567.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEzfBgB897pJ3nMCZstLkUf_E889_qEl4',
    appId: '1:124179968487:ios:bb5c5a7ea4f956c1ef8d42',
    messagingSenderId: '124179968487',
    projectId: 'knowledgematch-3a567',
    storageBucket: 'knowledgematch-3a567.appspot.com',
    iosBundleId: 'com.example.knowledgematch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEzfBgB897pJ3nMCZstLkUf_E889_qEl4',
    appId: '1:124179968487:ios:bb5c5a7ea4f956c1ef8d42',
    messagingSenderId: '124179968487',
    projectId: 'knowledgematch-3a567',
    storageBucket: 'knowledgematch-3a567.appspot.com',
    iosBundleId: 'com.example.knowledgematch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlS-5rA9AXrgY0U2-Mh3M4jBPL1jE3daA',
    appId: '1:124179968487:web:27ff8dc27338ea2aef8d42',
    messagingSenderId: '124179968487',
    projectId: 'knowledgematch-3a567',
    authDomain: 'knowledgematch-3a567.firebaseapp.com',
    storageBucket: 'knowledgematch-3a567.appspot.com',
    measurementId: 'G-4PTERTT01G',
  );

}